python scripts/gr00t_finetune.py \
    --train-dataset-path /home/innovation-hacking/luebbet/dev/important_datasets/experiments/01_kinematics/cal3_rand150_dim0-2_moving_target/ \
    --validation-dataset-path /home/innovation-hacking/luebbet/dev/important_datasets/experiments/01_kinematics/cal3_rand150_dim0-2_moving_target/ \
    --eval_steps 50 \
    --output-dir /home/innovation-hacking/luebbet/models/eval_09_05/AbsJoint-State_DeltaJoint-Action \
    --max-steps 111 \
    --data-config "tng_ur5_AbsJointState_DeltaJointAction_2Cams" \
    --embodiment-tag new_embodiment \
    --video-backend torchvision_av \
    --batch-size 16 \
    --no-tune-llm \
    --no-tune-visual \
    --tune-projector \
    --tune-diffusion-model \
    --report-to tensorboard \
